package router

import (
	"errors"
	"github.com/gin-gonic/gin"
	"github.com/sirupsen/logrus"
	"go-gen-apis/config"
)

func SetUpAutoGeneratedApis(cfg *config.GenApiConfig, ginEngine *gin.Engine) error {
	if cfg == nil {
		logrus.Error("cfg is nil")
		return errors.New("gen api cfg is nil")
	}

	return nil
}
