package router

import (
	"errors"
	"github.com/gin-gonic/gin"
	"github.com/sirupsen/logrus"
	"go-gen-apis/config"
	"go-gen-apis/handler"
	"go-gen-apis/repository"
	"go-gen-apis/repository/db"
	"go-gen-apis/service"
)

func SetUpAutoGeneratedApis(cfg *config.GenApiConfig, ginEngine *gin.Engine) error {
	if cfg == nil {
		logrus.Error("cfg is nil")
		return errors.New("gen api cfg is nil")
	}

	database, err := db.NewConnection(cfg)
	if err != nil {
		logrus.Errorf("failed to connecting postgres %v", err)
		return err
	}

	repo := repository.NewItemRepository(database)
	itemService := service.NewItemService(repo)
	itemHandler := handler.NewItemHandler(itemService)
	setupItemRoutes(ginEngine, itemHandler)
	return nil
}

func setupItemRoutes(engine *gin.Engine, itemHandler handler.ItemHandler) {
	itemsGroup := engine.Group("/items")
	{
		itemsGroup.POST("/:table_name", itemHandler.CreateItem)
		itemsGroup.GET("/:table_name", itemHandler.GetItems)
		itemsGroup.GET("/:table_name/:id", itemHandler.GetItemByID)
		itemsGroup.PUT("/:table_name/:id", itemHandler.UpdateItem)
		itemsGroup.DELETE("/:table_name/:id", itemHandler.DeleteItem)
	}

	logrus.Info("item routes configured successfully")
}
